name: free_vpn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  csv: ^5.0.2
  super_ui_kit:
    git:
      url: https://github.com/krzshipon/super_ui_kit.git
      ref: dev
  flutter: 
    sdk: flutter
  change_app_package_name: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/animations/

